apiVersion: v1
kind: Service
metadata:
  name: icinga2-web
  namespace: $NS
  labels:
    app: icinga2-web
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: icinga2-web
