PROPERTIES :=   streaming-platform.com  \
				streamnvr.com           \
				platformnvr.com

install:	; @for F in $(PROPERTIES); do $(MAKE) -C $$F install; done
delete:		; @for F in $(PROPERTIES); do $(MAKE) -C $$F delete; done
