FROM php:7.1-apache

RUN a2enmod rewrite

RUN apt-get update && apt-get install wget apt-transport-https -y && \
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list && \
    apt-get update && \
    apt search php7

# install the PHP extensions we need
RUN apt-get install -y libpng-dev libjpeg-dev libpq-dev libpcre3-dev \
  libcurl3 libcurl4-openssl-dev php7.2-cli wget build-essential php7.2-dev vim mysql-client \
	&& rm -rf /var/lib/apt/lists/* \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd mbstring opcache pdo pdo_mysql pdo_pgsql zip curl pcntl \
  && mkdir /app && rm /etc/apache2/sites-enabled/000-default.conf

COPY ./docker/config/apache/dodpt-vhost.conf /etc/apache2/sites-enabled/000-dodpt-vhost.conf
COPY ./docker/aws.credentials /.aws/credentials

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN { \
    echo 'log_errors=1'; \
    echo 'error_log=/tmp/php_errors.log'; \
  } > /usr/local/etc/php/conf.d/errors.ini

RUN { \
    echo 'post_max_size=200M'; \
    echo 'upload_max_filesize=200M'; \
  } > /usr/local/etc/php/conf.d/file-uploads.ini

VOLUME ["/app"]

# Install composer and install global drush
RUN cd /tmp \
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php composer-setup.php \
  && mv composer.phar /usr/local/bin/composer \
  && unlink composer-setup.php \
  && composer global require webflo/drush-shim \
  && ln -s /root/.composer/vendor/webflo/drush-shim/bin/drush /usr/local/bin/drush

# Install Drupal console launcher
RUN curl https://drupalconsole.com/installer -L -o drupal.phar \
  && mv drupal.phar /usr/local/bin/drupal \
  && chmod +x /usr/local/bin/drupal